### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by davecastlevania** [kremsku/codecademy-tdd#4]
Great job on this project so far. Jumping straight into TDD is always a challenging adventure and it appears to me that you are gaining a good foundation of understanding and practical knowledge. All your tests appeared to pass for me and the way your project was setup didn't cause me any major issues. I was able to clearly understand what you were testing for and you did an excellent job at this. Keep this up!

Summary: Beyond Expectation

**Comment by kremsku** [comment]
Thank you!
